//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junkbot_Reader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Junkbot_Reader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;scene&quot;: {
        ///      &quot;name&quot;: &quot;Loading&quot;,
        ///      &quot;tag&quot;: &quot;Loading&quot;,
        ///      &quot;zIndex&quot;: 0
        ///    },
        ///    &quot;gameObjects&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;FPSCounter&quot;,
        ///        &quot;position&quot;: {
        ///          &quot;x&quot;: 1,
        ///          &quot;y&quot;: 0
        ///        }
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;scene&quot;: {
        ///      &quot;name&quot;: &quot;LevelInterface&quot;,
        ///      &quot;tag&quot;: &quot;LevelInterface&quot;,
        ///      &quot;need&quot;: [
        ///        &quot;Level&quot;
        ///      ],
        ///      &quot;zIndex&quot;: 10
        ///    },
        ///    &quot;gameObjects&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;BrickHandler&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdditionalScenes {
            get {
                return ResourceManager.GetString("AdditionalScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : The following required arguements were not provided :
        ///	&lt;SourcePath&gt;
        ///	&lt;TargetFile&gt;
        ///
        ///USAGE :
        ///	Junkbot Reader.exe &lt;SourcePath&gt; &lt;TargetFile&gt;
        ///
        ///For more information, try --help.
        /// </summary>
        internal static string Error0 {
            get {
                return ResourceManager.GetString("Error0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : The following required arguements were not provided :
        ///	&lt;TargetFile&gt;
        ///
        ///USAGE :
        ///	Junkbot Reader.exe &lt;SourcePath&gt; &lt;TargetFile&gt;.
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION : Converts Junkbot fff level files to an ORB json file.
        ///
        ///USAGE :
        ///	Junkbot Reader.exe &lt;SourcePath&gt; &lt;TargetFile&gt;
        ///
        ///ARGS :
        ///    &lt;SourcePath&gt;    The source path for Junkbot fff files.
        ///    &lt;TargetFile&gt;    The destination of the resulting ORB json file..
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
    }
}
